### ISSUE TITLE
Making it possible to call super trait methods with bound on the subtrait

### ISSUE THREAD

**Issue by fee1-dead** [rust-lang/project-const-traits#2]
We'll start with the sugar version:

```rust
#[const_trait]
trait Foo {
    fn a(&self);
}

#[const_trait]
trait Bar: ~const Foo {}

const fn foo<T: ~const Bar>(t: &T) {
    t.a();
}
```

This currently fails compilation, and making a desugaring that makes this work is apparently hard. I'll illustrate this issue by first desugaring it.

Note that this desugaring uses some types from a PR that has not yet landed. See [this diff](https://github.com/rust-lang/rust/pull/128781/files#diff-a7b0a003ba552d18884d9ad49a45c6db54bb9f6b24658b7f0b417b6aaceee25a) for more info.

```rust
trait Foo {
    type Fx;
    fn a<const RUNTIME: bool>(&self) where Param<RUNTIME>: Sub<Self::Fx>;
}

trait Bar: Foo {
    type Fx: Sub<<Self as Foo>::Fx>;
}

fn foo<const RUNTIME: bool, T: Bar>(t: &T) where Param<RUNTIME>: Sub<<T as Bar>::Fx> {
    t.a();
}
```

This errors because the bound on `Foo::a` isn't satisfied (specifically `Param<RUNTIME>: Sub<Self::Fx>`) Now one way to do this is maybe make the compiler know that `Sub` is a transitive trait, such that `A: Sub<B>, B: Sub<C>` would together imply `A: Sub<C>`. But that could be very complicated.

I'm not entirely sure how else to approach it. There might be other desugarings that would make this work, but none was able to escape this transitive implication thing I think.

**Comment by PoignardAzur** [comment]
> I'm not entirely sure how else to approach it. There might be other desugarings that would make this work, but none was able to escape this transitive implication thing I think.

Stop me if I'm being naive, but how hard would it be to just hardcode the list of supertraits in the desugared bounds? (Now that's a tongue-twister.)

So your example could desugar to this:

```rust
fn foo<const RUNTIME: bool, T: Bar>(t: &T)
where
    Param<RUNTIME>: Sub<<T as Bar>::Fx>,
    Param<RUNTIME>: Sub<<T as Foo>::Fx>,
{
    t.a();
}
```

It's not *super* efficient, but I'm pretty sure 99.9% of trait hierarchies in any Rust codebase have under five traits in them, so this solution doesn't add huge amounts of extra work.

EDIT - Oh, this is basically https://github.com/rust-lang/rust/pull/129499

**Comment by compiler-errors** [comment]
This should be finished ✨
